import { Inter } from "next/font/google";
import "./globals.css";
import FlashSectionRoute from "./@fleshSection/page";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Exclusive",
  description: "Generated by create next app",
};

export default function RootLayout({ children, fleshSection }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        {/* <FlashSectionRoute /> */}
        {/* {fleshSection} */}
      </body>
    </html>
  );
}
